name: arduino-cli
base: core18
version: '0.25.0'
architectures:
  - build-on: [arm64, armhf, amd64, i386]
summary: Arduino command-line interface
description: |
  Arduino CLI is an all-in-one solution that provides builder, boards/library manager,
  uploader, discovery and many other tools needed to use any Arduino compatible
  board and platforms.

  **Note**: this software is currently under active development: anything can change
  at any time, API and UI must be considered unstable until we release version 1.0.0.

  **Necessary plugs**
  If you are not able to list and/or upload to your board, you may need plugs and connects.
  See `snap connections arduino-cli` for necessary plugs (such as access to USB and serial ports) and connect them with 

  `$ sudo snap connect arduino-cli:<plug>`
  
  where `<plug>` can be in example `raw-usb`.

  **Optional plugs**
  - *raw-usb:* allows access to all connected USB devices via a raw interface.
  - *serial-port*: enables access to a specific serial port. This interface is restricted because it provides privileged access to configure serial port hardware. Might require hot-plug support `snap set system experimental.hotplug=true` followed by `systemctl restart snapd`.  

grade: stable
confinement: strict

apps:
  arduino-cli:
    command: usr/bin/arduino-cli
    plugs:
    - network
    - serial-port
    - raw-usb
    - home

parts:
  arduino-cli:
    plugin: dump
    source:
      - on amd64: https://github.com/arduino/arduino-cli/releases/download/$SNAPCRAFT_PROJECT_VERSION/arduino-cli_$SNAPCRAFT_PROJECT_VERSION_Linux_64bit.tar.gz
      - else:
        - on i386: https://github.com/arduino/arduino-cli/releases/download/$SNAPCRAFT_PROJECT_VERSION/arduino-cli_$SNAPCRAFT_PROJECT_VERSION_Linux_32bit.tar.gz
      - else:
        - on armhf: https://github.com/arduino/arduino-cli/releases/download/$SNAPCRAFT_PROJECT_VERSION/arduino-cli_$SNAPCRAFT_PROJECT_VERSION_Linux_ARMv7.tar.gz
      - else:
        - on arm64: https://github.com/arduino/arduino-cli/releases/download/$SNAPCRAFT_PROJECT_VERSION/arduino-cli_$SNAPCRAFT_PROJECT_VERSION_Linux_ARM64.tar.gz
      - else fail
    build-packages:
      - wget
    organize:
      arduino-cli: usr/bin/
      LICENSE.txt: usr/share/arduino-cli/

